### ISSUE TITLE
Refresh problem

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/InstallationValidator#107]
During the **_Calculation_** of batch simulation user does not see any progress.
Once the info _N simulations found..._ is shown no more information messages are displayed until the calculation is finished and the **_Validation_** starts.

During _validation_ UI is refreshed properly
![iv_01](https://cloud.githubusercontent.com/assets/25061876/26551217/a7da2428-4481-11e7-9472-0fd6e7ea9a47.jpg)

**Comment by msevestre** [comment]
Cannot reproduce. This works fine on VM Win7 SP1 as well as Windows 10. They may be a slight delay sometimes. It could be an issue with the VM you are using
Have you tried on other VMs / real machine?

**Comment by msevestre** [comment]
the 
`info:...`  section comes from the log file itself. That means that the log file is read properly. 
How many cores do you have on the vm? i

**Comment by Yuri05** [comment]
>Have you tried on other VMs / real machine?

Tried on different VMs and also on my physical PC (4 cores) - always the same (no refresh till all simulations are calculated)

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/26879109-e27be0b6-4b5d-11e7-990c-46b86219cea3.png)
Just tried with suite setup on empty vm....

Are you changing the default output path to a server somewhere? Maybe that's the issue

**Comment by msevestre** [comment]
ah ah wait. I think it refreshed because I had the explorer Window open!

**Comment by msevestre** [comment]
@rwmcintosh I can reproduce on empty VM: If the explorer Window is open, refresh is happening. If not, then no refresh going on
