### ISSUE TITLE
Total page number missing in footnote

### ISSUE THREAD

**Issue by hdiedam** [Open-Systems-Pharmacology/InstallationValidator#112]
The validation report contains only a placeholder "??" for the total page number.

![footnote](https://user-images.githubusercontent.com/26765701/26934200-020c8ed8-4c69-11e7-86d3-d98030d0716b.PNG)

**Comment by hdiedam** [comment]
Just wanted to add that the table of content is empty as well. Quite likely both a consequence of #99 , because you need the second Latex run for references, TOC, final page number, ...

**Comment by msevestre** [comment]
@yes absolutely. 
Well let's add another run then :) Funny enough it works sometimes but as it seems not all the time

**Comment by msevestre** [comment]
going to set the number of run to 2. PK-Sim and MoBi use 3 but it might be overkill here . Going to try to generate a full report again and see how it behaves

**Comment by msevestre** [comment]
![image](https://user-images.githubusercontent.com/1041237/27152430-d404b698-511b-11e7-833f-7ec651681ce7.png)

Works with 2 iterations

**Comment by msevestre** [comment]
and
![image](https://user-images.githubusercontent.com/1041237/27152492-0960d6b4-511c-11e7-8a52-d83a989db4f4.png)
