### ISSUE TITLE
Installation validator - Problem

### ISSUE THREAD

**Issue by nmens** [Open-Systems-Pharmacology/InstallationValidator#117]
Dear all
I've tried to run Installation validator. However, an error message apears (copied below):

«Starting batch calculations...

oops...something went terribly wrong.

Value cannot be null. Parameter name: path1 For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org). Stack trace: at System.IO.Path.Combine(String path1, String path2) at InstallationValidator.Core.InstallationValidatorConfiguration.get_PKSimBatchToolPath() at InstallationValidator.Core.Services.BatchStarterTask.startBatchProcess(String outputFolderPath, CancellationToken cancellationToken, String logFile) at InstallationValidator.Core.Services.BatchStarterTask.<>c__DisplayClass5_0.b__0() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at InstallationValidator.Core.Services.BatchStarterTask.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at InstallationValidator.Core.Presentation.MainPresenter.d__11.MoveNext()
---------------------------------
Any idea to complete the validation process?
Many thanks in advance

Rgs
NS

**Comment by rwmcintosh** [comment]
That indicates a path to the PK-sim batch tool could not be found in the registry. Did you do a full installation of 7.1?

**Comment by nmens** [comment]
Hello rwmcintosh
Thanks for your fast reply. I have uninstalled Suite 7.1, installed again and run installation validator. Everything worked fine for this time. All tests were passed successfully. 
Rgs
NS

**Comment by msevestre** [comment]
@nmens Did you receive a message by any chance that a restart was required after the firs install?
