### ISSUE TITLE
Importing observing data

### ISSUE THREAD

**Issue by nmens** [Open-Systems-Pharmacology/InstallationValidator#118]
Dear all

First attempt with PK Sim. Observed data button on Imported/Exported tab is blocked (grey color). It is only possible to import Fraction Data. Being in mind that Fraction Data is for dissolution data, should I also use it for PK concentration data? Why Observed data button is blocked?

Rgds
NS

**Comment by msevestre** [comment]
For question and how to, please post in the forum. InstallationValidator is not the place to ask question about PK-Sim. Thanks

**Comment by nmens** [comment]
Sorry for my inexperience! I moved the question into Forum.
Rgds
