### ISSUE TITLE
Calculate new outputs

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/InstallationValidator#139]
[Output batch files](https://github.com/Open-Systems-Pharmacology/InstallationValidator/tree/develop/data/Outputs/BatchFiles) must be recalculated.
Starting Installation Validator **7.3.0.6** produces some INVALID comparisons - probably because batch outputs were calculated with the version having some bugs in snapshot import

```
Comparing files 'European_SingleORAL_Age_0_CYP3A4.json'...Invalid
Comparing files 'Human_MultipleIV_AllActiveProcesses.json'...Invalid
Comparing files 'Human_MultipleIV_transporters.json'...Invalid
Comparing files 'Test 18.1_I2_C3_A1_Config2.json'...Invalid
Comparing files 'Test 18.1_I3_C3_A3_Config2.json'...Invalid

```

**Comment by msevestre** [comment]
Output were not calculate for 7.3

**Comment by Yuri05** [comment]
>Output were not calculate for 7.3

That was my hope (otherwise we would have a problem here)
