### ISSUE TITLE
Export language settings as part of the validation summary

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/InstallationValidator#160]
Extend the **Validation Summary** section of validation report with the current language settings
(`Thread.CurrentThread.CurrentCulture.Name`)

**Comment by msevestre** [comment]
That won't work. We override this settings to make sure we are always en-US.

**Comment by msevestre** [comment]
Although maybe we could save the settings before updating it somehow since this will be used for display only

**Comment by Yuri05** [comment]
Would be enough to get current culture info before overriding
