### ISSUE TITLE
Validation report could not be created

### ISSUE THREAD

**Issue by rxtms** [Open-Systems-Pharmacology/InstallationValidator#163]
I was running the Installation Validator, but got the following error messages., not sure what's wrong?

Number of compared files: 125
Overall comparison result: Valid

Starting report creation...
oops...something went terribly wrong.
To best address the error, please enter an issue in our issue tracker:
1.Visit https://github.com/Open-Systems-Pharmacology/InstallationValidator/issues or click on the link below
2.Click on the New Issue button
3.Describe the steps you took prior to the problem emerging
4.Copy the information below by using the Copy to Clipboard button and paste it in the issue description
5.if possible, attach your project file to the issue (do not attach confidential information)
Note: A GitHub account is required to create an issue

Report could not be created. Please see log for details located under 'C:\Outputs\bd4a221d-e9fe-43df-ad2e-a0332545a20a' For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org). Stack trace: at OSPSuite.TeXReporting.ReportCompiler.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at OSPSuite.TeXReporting.ReportCreator.d__6`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at OSPSuite.Infrastructure.Reporting.ReportingTask.d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at InstallationValidator.Core.Services.ValidationReportingTask.d__6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at InstallationValidator.Core.Presentation.MainPresenter.d__11.MoveNext()

**Comment by msevestre** [comment]
@rxtms May I suggest to restart the computer and try again.
Report creation takes a while and crashes sometime when the computer memory is under load.

Let me know if that solves the issue,

Thanks,
Michael

**Comment by rxtms** [comment]
The problem was solved by removing the existing MikTex installation on my computer. That installation was probably a faulty to start with.

**Comment by msevestre** [comment]
So you had an existing miktek already. Interesting. Probably the same issue as #162

**Comment by msevestre** [comment]
Closing

**Comment by rxtms** [comment]
Thanks Michael. I don't have any experience with miktex (perhaps a leftover from some old programs), but it does sound like the same issue.
