### ISSUE TITLE
Creation of subcutaneous compartment for small molecule

### ISSUE THREAD

**Issue by biju-benjamin** [Open-Systems-Pharmacology/InstallationValidator#164]
I am trying to incorporate a subcutaneous compartment into a  working iv-PBPK model to be used for  population simulation. The idea is to use de-convolved cumulative-fraction absorbed profile as input from subcutaneous  to plasma assuming no clearance in the subcutaneous compartment

I am  new to OSP however is quite familiar with underlying PBPK models more so using  C -compilers.  The following are the steps I followed

**with PK-sim** 
created a custom administration profile with skin as the target organ and interstitial space as target compartment. 
A table formulation was created with cumulative fraction absorbed as table values.  Simulation worked
As a second step changed the target compartment to plasma and repeated the simulation . Both results look alike visually. 

**_Question -1_**
I doubt any of the above is the correct approach to my problem considering  that de-convolution provides an input to plasma from the extra-vascular site-  Any recommendations

**With Mobi**

Exported the working iv population simulation  as pkml
created a spatial structure for subcutaneous, defined neighborhood  with venous plasma. 
Created a global compound parameter"'Sc_abn" with table as formula type ,  fraction as dimension and input the de-convolution  data into table.
 In the passive transport building block  created a new property  "SubcutaneousAbsorption *  with a formula 
Sc_abn* concentration

mapping with "concentration" (found under organism/Subcutaneous/Compound). 

For simulation in Mobi - couldn't figure the correct way (might need to spend more time with the manual, I guess) , so did the following

a) set  the molecule start value in subcutaneous compartment equal to dose, defined and executed a  simulation  It provides an output-  , is that the correct way to do -changing molecule start value each time
b) Created a simulation profile and exported to PK-sim expecting a Subcutaneous compartment to come up  in the user defined administration protocol of PK-sim- disappointed- Is there a way to get it there

**Question -2**

 What could be the simplest way to get the task done with Mobi  ? 

Thanks in advance

Biju Benjamin

**Comment by msevestre** [comment]
@biju-benjamin May I suggest to add this question in the forum. Entering the issue in the InsallationValidator with result in no-one seeing it and as such you want get any help

Simply copy paste your entry in the forum. 
Good luck
Michael

**Comment by biju-benjamin** [comment]
Thanks Michael, did that just now. 
sorry about posting at the wrong place.
B
