### ISSUE TITLE
SimulationOutputsComparer: Wrong scale in the lin plots?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/InstallationValidator#217]
Looking at the pdf here: https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1759#issuecomment-843314474

On the pages 4-6 there is a plot for **OrganismjSmallIntestinejMucosajDuodenumjIntracellularjClarithromycin-CYP3A4-
t MetabolitejFraction of dose-Clarithromycin** in log and lin scale.
In the lin scale the Y-values in the plot legend do not match the Y-Values in the log scale at all!
Log scale: values are between 0.001 and 0.01 and lin scale between 2 and 7
(in the lin scale also the plot **caption** is not properly displayed - but that's a minor issue)

![grafik](https://user-images.githubusercontent.com/25061876/119484977-d860ed00-bd56-11eb-8e08-59acb61c7ea4.png)
![grafik](https://user-images.githubusercontent.com/25061876/119485622-96847680-bd57-11eb-9653-14880d17fbef.png)
![grafik](https://user-images.githubusercontent.com/25061876/119485122-fe868d00-bd56-11eb-9dfd-d8dad7b60de0.png)

**Comment by Yuri05** [comment]
Ah ok, I know what happend: there is actually 10<sup>-N</sup> in the scale but because the plot caption is so long it's messed up:
![grafik](https://user-images.githubusercontent.com/25061876/119486733-ddbf3700-bd58-11eb-96ad-d7189778c080.png)

That's how it looks like in the plots with shorter caption:
![grafik](https://user-images.githubusercontent.com/25061876/119486837-fb8c9c00-bd58-11eb-9812-51a1081efcc2.png)

So it's just a UI issue.

**Comment by msevestre** [comment]
those plots are created with MikText.. no chance for me to fix this so...I'll suggest to accept this:)
