### ISSUE TITLE
SimulationComparer: Differences not shown

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/InstallationValidator#218]
When running the snapshot [DDI_MultipleCombinations_EffluxOnly.zip](https://github.com/Open-Systems-Pharmacology/InstallationValidator/files/6546086/DDI_MultipleCombinations_EffluxOnly.zip) with the BatchRunner in V9 and V10 and comparing the simulation results: only 6 out of 23 simulations are shown as invalid:

<details><summary><b>Simulation output comparer output</b></summary>

```
Starting output comparisons...
Comparing files 'DDI_MultipleCombinations_EffluxOnly-01_MM_Competitive_Competitive.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-02_MM_Uncompetitive_Uncompetitive.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-03_MM_Noncompetitive_Noncompetitive.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-04_MM_Mixed_Mixed.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-05_MM_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-06_MM_Induction_Induction.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-07_MM_Competitive_Competitive_Mechanismbased_Mechanismbased.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-08_MM_Uncompetitive_Uncompetitive_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-09_MM_Noncompetitive_Noncompetitive_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-10_MM_Mixed_Mixed_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-11_MM_Mechanismbased_Mechanismbased_Induction_Induction.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-12_MM_All_DDI_Types.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-21_1st_Competitive_Competitive.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-23_1st_Noncompetitive_Noncompetitive.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-24_1st_Mixed_Mixed.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-25_1st_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-26_1st_Induction_Induction.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-27_1st_Competitive_Competitive_Mechanismbased_Mechanismbased.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-28_1st_Uncompetitive_Uncompetitive_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-29_1st_Noncompetitive_Noncompetitive_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-30_1st_Mixed_Mixed_Mechanismbased_Mechanismbased.json'...Valid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-31_1st_Mechanismbased_Mechanismbased_Induction_Induction.json'...Invalid
Comparing files 'DDI_MultipleCombinations_EffluxOnly-32_1st_All_DDI_Types.json'...Valid
```

However ALL simulations should be shown as invalid due to the change of the Efflux/Basolateral transporter location between V9 and V10 (Intracellular==>Interstitial)
![grafik](https://user-images.githubusercontent.com/25061876/119645407-491f0c80-be1e-11eb-9265-2a08f10f1b6a.png)
</details>

E.g. for the simulation **01_MM_Competitive_Competitive** "`P-gp|Bone|Intracellular|Concentration`" is ca. 0.04 µmol/l in V9 and ZERO in V10
<details><summary><b>P-gp|Bone|Intracellular|Concentration</b> V9 and V10</summary>

![grafik](https://user-images.githubusercontent.com/25061876/119646728-c6974c80-be1f-11eb-9696-7026651cd88d.png)
![grafik](https://user-images.githubusercontent.com/25061876/119646844-ea5a9280-be1f-11eb-90f8-7186a74702a3.png)

</details>

Attached is batch output for the simulation **01_MM_Competitive_Competitive** in V9 and V10
[output.zip](https://github.com/Open-Systems-Pharmacology/InstallationValidator/files/6546132/output.zip)

**Comment by msevestre** [comment]
@Yuri05 
This is the code 
https://github.com/Open-Systems-Pharmacology/InstallationValidator/blob/develop/src/InstallationValidator.Core/Domain/PointwiseComparisonStrategy.cs#L112

I can't remember why we have this "ComparisonThreshold" it's always the value of the output1 for some reason. 
At any rate, with a value of 0.039 and 0 and threshold = 0.039, the deviation is 1 but value1 and value2 are <- threshold

Therefore => all seems the same. we also have tests for this. WHY is this like that??

**Comment by msevestre** [comment]
oh.that's generated from SimModel?

**Comment by Yuri05** [comment]
yep. just created a PR in SimModel to fix it

**Comment by msevestre** [comment]
ok...we need to update quite a bunch of packages when SimModel changes.. on it

**Comment by msevestre** [comment]
ok so it's not a bug

**Comment by msevestre** [comment]
at least not from the comparison too.
