### ISSUE TITLE
Exclusions list must appear in the report

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/InstallationValidator#222]
At the moment exclusions list is shown only in the comparison tool but is not included into the pdf report.
![grafik](https://user-images.githubusercontent.com/25061876/122371125-e96cda80-cf5f-11eb-9ca4-0589d0b394ac.png)

**Comment by Yuri05** [comment]
almost :)
just missing the newlines between entries and `<b>` 

![grafik](https://user-images.githubusercontent.com/25061876/122452418-86a03100-cfa9-11eb-8c32-611a73a9990e.png)

**Comment by msevestre** [comment]
Where did you get that pdf from? IF this is the one I sent, then it was before the fix

**Comment by Yuri05** [comment]
yes, that was from your pdf
