### ISSUE TITLE
Errors reported by Installation Validator

### ISSUE THREAD

**Issue by zt1947** [Open-Systems-Pharmacology/InstallationValidator#272]
Following the download and installation of OPEN SYSTEMS PHARMACOLOGY SUITE - VERSION 11 UPDATE 3, the Installation Validator reported errors described in the enclosed file:  
[There is something wrong with the Open Systems Pharmacology.docx](https://github.com/Open-Systems-Pharmacology/InstallationValidator/files/15063415/There.is.something.wrong.with.the.Open.Systems.Pharmacology.docx)
I would be grateful for assistance in solving the issues reported there.

**Comment by Yuri05** [comment]
It seems that the installation of MikTex (pdf engine) failed or is corrupted.
Did you get any errors/warnings during the OSP Suite installation?
Please try to reinstall this component manually ([MikTex setup](https://github.com/Open-Systems-Pharmacology/MiKTeX/releases/download/v2.9.3/MikTex.2.9.3.msi))

**Comment by zt1947** [comment]
Dear Juri,
Thanks for your comment!
It seems that unlike in previous downloads , this time MikTex did
not download at all!
Is there a way to download it without deleting the recent download and
starting the download procedure from scratch?
Sincerely
Zvi Teitelbaum

**Comment by Yuri05** [comment]
use the link above to download the MikTex setup and install it.
