### ISSUE TITLE
Something is broken in the simulation comparison

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/InstallationValidator#277]
After https://github.com/Open-Systems-Pharmacology/InstallationValidator/issues/269 was fixed, I tried to compare V12 with V11 and got a lot of deviations.
However, most (all?) of them seem to be in the "numerical noise" range and should be ignored.

<details><summary>Even for Fractions, where the comparison threshold is per construction set to <b>>= 1e-4</b> deviations in much smaller ranges are suddenly reported.</summary>

![grafik](https://github.com/user-attachments/assets/dbff4d48-186b-46a2-8711-fedf6c4e266e)
</details> 

I then tried to compare some intermediate state of V12 (which does not crash when using OutputsComparer 11.3) with V11 **using the OutputsComparer 11.3** - and then the most deviations disappeared.

E.g. in this example there is just 1 simulation: [4mail.zip](https://github.com/user-attachments/files/16455849/4mail.zip)

When comparing with OutputsComparer 11.3 - no deviations:
<img width="500" src="https://github.com/user-attachments/assets/ba046fe1-9592-429b-829d-aa1f6d5f768e">

When comparing with OutputsComparer 12.0 - deviations are reported ([Open Systems Pharmacology Suite - 12-Installation Validation_08_01_24_13_42_51.pdf](https://github.com/user-attachments/files/16455597/Open.Systems.Pharmacology.Suite.-.12-Installation.Validation_08_01_24_13_42_51.pdf)
<img width="500" src="https://github.com/user-attachments/assets/96da0d3d-a5e8-4772-8222-f8ae88e0923d">

**Comment by msevestre** [comment]
Interesting....going to check this out

**Comment by msevestre** [comment]
ok so there is no threshold defiend in the json file
For some reason, the value of the threshold for output1 is 0 when loaded from json

**Comment by msevestre** [comment]
I don't know where this json file is coming from lol but this is weird.

**Comment by msevestre** [comment]
@Yuri05 Can you attach a project so thatI can reproduce? I only see one difference with the 4mail project

![image](https://github.com/user-attachments/assets/c26a7d47-3f8e-48eb-9a9d-76e7304b5d7f)

in this case, we have value1 = 0 and value2 !=0 

![image](https://github.com/user-attachments/assets/c88bebde-d4c3-4003-af91-eebb41fbf3d0)

so the difference is infinity. I am not sure what we should do in this case. For me the difference reported are accurate however
I am going to update the code to use at least one threshold if one is defined

**Comment by Yuri05** [comment]
> Can you attach a project so thatI can reproduce?

The simulation outputs were created by the PK-Sim Batch Runner (version 11.2 and version 12.0) based on the batch input https://github.com/Open-Systems-Pharmacology/InstallationValidator/blob/develop/data/Inputs/BatchFiles/DDI_MultipleCombinations.json 

In fact, this problem occurred for a lot of simulations when comparing 11.2 outputs vs 12.0 outputs - I just randomly selected one of the examples.

E.g. here a full comparison report  - most (all?) of the differences is just a numerical noise due to ignored threshold. 
[Open Systems Pharmacology Suite - 12-Installation Validation_07_31_24_17_52_55.pdf](https://github.com/user-attachments/files/16847175/Open.Systems.Pharmacology.Suite.-.12-Installation.Validation_07_31_24_17_52_55.pdf)

**Comment by Yuri05** [comment]
> ok so there is no threshold defiend in the json file For some reason, the value of the threshold for output1 is 0 when loaded from json

Which output is that? I checked for the first 4 outputs reported as different in the comaprison report  - and the threshold is the same in both output files and not a zero.

**Comment by msevestre** [comment]
ok so the problem is not with the simulation comparison
![image](https://github.com/user-attachments/assets/85d08f45-b87a-4415-b2e0-c52829d5cde4)

for some values, the previous value was 0 and now it's not. 
![image](https://github.com/user-attachments/assets/d5e58574-3885-447c-a853-5978bf4ef947)


so the deviation becomes infinity. What should we do to prevent this? if the value are below the absolute tolerance, should we set them to abs tolerance? or sthg like this. Or return 0 for deviation?

**Comment by msevestre** [comment]
in this case, value1 is 0 and value2 is 4.E-10

**Comment by Yuri05** [comment]
> in this case, value1 is 0 and value2 is 4.E-10

Yes, but the threshold for `Organism|Lumen|Stomach|Fluvoxamine|Concentration in lumen` is set in both files to **1.0** - and both values are below 1.0 - so the comparison should return `deviation=0` ??

> What should we do to prevent this? if the value are below the absolute tolerance, should we set them to abs tolerance? or sthg like this. Or return 0 for deviation?

actually, the code below handles exactly this use case. I'm confused..
https://github.com/Open-Systems-Pharmacology/InstallationValidator/blob/335489589ba91e4fec14e86ad50bef9dac8ed193/src/InstallationValidator.Core/Domain/PointwiseComparisonStrategy.cs#L133-L134

**Comment by msevestre** [comment]
ok so we are back to the threshold not being read properly. Ok let me debug this again.

**Comment by msevestre** [comment]
ok so
1, Threshold was nto copied over in the routine making the conversion
2. the 12.0 file is corrupted
![image](https://github.com/user-attachments/assets/4fbd3eac-d0c6-4435-96f7-a0b04614df8c)

this is not a valid structure for Time. (or we are doing something wrong). Did you JUST generate this file?

**Comment by msevestre** [comment]
![image](https://github.com/user-attachments/assets/c06441c9-7b2b-4190-99dd-761d654e38e3)

@Yuri05 v12 file are not respecting the format that we have in core. WTF??

**Comment by Yuri05** [comment]
> Did you JUST generate this file?

No. The file was created by the batch runner 12.0.x from the end of last year (because I needed the version which I could compare both by v11 and v12 SimulationComparer).

This one was created 1 month ago: [DDI_MultipleCombinations-01_MM_Competitive_Competitive.zip](https://github.com/user-attachments/files/16849682/DDI_MultipleCombinations-01_MM_Competitive_Competitive.zip)
Same picture in the comparison between 11.2 and 12.0: [Open Systems Pharmacology Suite - 12-Installation Validation_09_03_24_15_44_44.pdf](https://github.com/user-attachments/files/16849819/Open.Systems.Pharmacology.Suite.-.12-Installation.Validation_09_03_24_15_44_44.pdf)

**Comment by msevestre** [comment]
ok this one is correct
![image](https://github.com/user-attachments/assets/406fd762-b3a3-45eb-a9fb-febbc9748e8c)

so with the fix from above, everything should be fine.

**Comment by msevestre** [comment]
can you get latest InstallationValidator and tyr again?

**Comment by Yuri05** [comment]
hoho, at least for this one file it works now! 👍 
![grafik](https://github.com/user-attachments/assets/dca04683-c7c1-4c76-b038-1bf470f07d8e)

Let's see how the full comparison looks like :)

**Comment by Yuri05** [comment]
ok, almost. "just" 3 invalid simulations now :) (compared to 76 "invalid" simulations before)
[Open Systems Pharmacology Suite - 12-Installation Validation_09_03_24_16_40_10.pdf](https://github.com/user-attachments/files/16850557/Open.Systems.Pharmacology.Suite.-.12-Installation.Validation_09_03_24_16_40_10.pdf)

**Comment by Yuri05** [comment]
sure, here are the output for the 3 invalid simulations and the report.
However now we have the real differences (clearly visible at least in some curves)
[03.09.2024.zip](https://github.com/user-attachments/files/16851428/03.09.2024.zip)

**Comment by msevestre** [comment]
oh so the difference is legit then?

**Comment by Yuri05** [comment]
ideally we should not have any differences here. investigating..

**Comment by msevestre** [comment]
ok. Plesae let me know (let's open another issue because I don't get notification on closed issue lo)
