### ISSUE TITLE
Move Exception message to core and reorganize Exception View to use html

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/InstallationValidator#88]

**Comment by msevestre** [comment]
see
```
 // TODO - change the implementation in Core and modify ExceptionView to use a RichEditControl instead of a label if the text does not display correctly
      public static string ExceptionViewDescription(string issueTrackerUrl)
      {
```

**Comment by rwmcintosh** [comment]
![image](https://cloud.githubusercontent.com/assets/261477/25762135/909ba112-31ab-11e7-9b8e-ab26d88bfe18.png)

Pretty close. The old one is on the right and newest is on the left.

We can do anything with css, but to make it look exactly like the old one we might have to change <p> to <br/>.

Thoughts?
