### ISSUE TITLE
Report: Additional section for plots

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/InstallationValidator#94]
New section should be added to the validation report: _Plots of **successful** simulations_
For every **successful** simulation: add simulation name and plots of few predefined curves in lin and log scale.

tbd. List of predefined curves.

**Comment by msevestre** [comment]
I would strongly advise against that. The report generation time increased
drastically and dramatically with the number of plots. Successful plots are
meaningless

**Comment by JLPangloss** [comment]
Disagree with meaningless argument. It has relevance for level of trust and provides one additional layer for QC process. Suggest to evaluate an option where low percentage of successful simulations is picked for plotting at random. Percentage should depend on total number. If O(10^5) simulations is performed, <=1% would already suffice to provide pretty robust feeling for what "success" may mean

**Comment by msevestre** [comment]
> It has relevance for level of trust 
What does that mean? A successful comparison (e.g Valid state) means that the curves are EXACTLY the same according to a predefined tolerance. The plots will always look the same

**Comment by msevestre** [comment]
@Yuri05
At any rate, please let us know which plots should be automatically generated.

**Comment by msevestre** [comment]
[Open Systems Pharmacology Suite - 7.1.0-Installation Validation_05_08_17_15_45_53.pdf](https://github.com/Open-Systems-Pharmacology/InstallationValidator/files/984674/Open.Systems.Pharmacology.Suite.-.7.1.0-Installation.Validation_05_08_17_15_45_53.pdf)

Example of file generated for 4 simulations . Time of pdf creation increased from 6 sec to 1 min.
I am going to start the comparison for all batch files and see how long it takes to create the pdf report

**Comment by Yuri05** [comment]
My proposal would be just to show per simulation only Peripheral Venous Blood/Plasma in log scale.
If more than 1 compound available: all in the same plot

**Comment by msevestre** [comment]
>If more than 1 compound available: all in the same plot
This would require some serious change in the implementation. Right now, our reporting component for output do not know anything about other outputs. 

>For every successful simulation: add simulation name and plots of few predefined curves in lin and log scale
So only log then? (lin was requested in the task description)

**Comment by Yuri05** [comment]
>This would require some serious change in the implementation. Right now, our reporting component for output do not know anything about other outputs.

But the reporting component knows the names of the curves and could just filter all curves containing peripheral venous bloos plasma, right?

>So only log then?

If it takes so much time for plotting - only log

**Comment by msevestre** [comment]
Filtering is supported. In the attached example, I am only showing two output curves. This no problem. 

Your request is however to put more than **one output** in a plot. We would need to change how we organize our report infrastructure

**Comment by msevestre** [comment]
Here are the results of my current try
* 113 Simulations
* All simulation valid
* 2 Curve per simulation, 2 plots per curve (lin and log)

Time to create PDF: 30min!

The log file indicates a lot of errors generating those plots. Fixing the pdf component is outside of the scope of the task at hand however

And as you can see in the attached pdf, those plots are meaningless
[Open Systems Pharmacology Suite - 7.1.0-Installation Validation_05_08_17_16_01_48.pdf](https://github.com/Open-Systems-Pharmacology/InstallationValidator/files/984796/Open.Systems.Pharmacology.Suite.-.7.1.0-Installation.Validation_05_08_17_16_01_48.pdf)

**Comment by msevestre** [comment]
(Looking at the pdf, we also have plots for CYP3A4 etc...). We do not have the information required at the moment from the batch output to decide if the value is a compound or an enzyme. Plots are created for all molecules defined in the simulations

**Comment by Yuri05** [comment]
Ok, so looking at the numbers above, I would suggest:
* only log scale plots
* all outputs from the simulation containing **PeripheralVenousBlood/Plasma** and NOT containing **CYP3A4** (we have also some other enzymes, transporters etc. in the test simulations, but in the most cases it's CYP3A4)
* one output per plot
* Option (checkbox) in the Installation Validator, allowing switching **valid** plots on and off (**invalid** plots will be reported in any case)
  * Default is ON

@JLPangloss Please comment

**Comment by msevestre** [comment]
Second try:
* 113 Simulations
* All simulations valid
* Only one log plot for valid simulations

Time to create PDF: 15min

**Comment by msevestre** [comment]
(Peripheral Venous blood does not exist for CYP3A4 so no need to filter)

**Comment by msevestre** [comment]
15min as good as it gets with the current report component. As mentioned earlier, some error are thrown from the latex component but I have no idea what they mean or even if these errors have any bearing on the generation speed. Our miktex package is also using fairly outdated components. Maybe a good task would be to try to update those components to latest and see if the speed increases. Suggestion would be to ask Bernd to do that

**Comment by msevestre** [comment]
the new comparison tool that compares an OLD and NEW folder, will bypass this new plots altogether. No need for these kind of noise there!

**Comment by Yuri05** [comment]
>the new comparison tool that compares an OLD and NEW folder, will bypass this new plots altogether. No need for these kind of noise there!

Agree!
